[package]
name = "wedder"
version = "0.1.0"
authors = ["Adrian Wersching <dev@awersching.de>"]
edition = "2018"

[dependencies]
confy = "0.3.1"
reqwest = "0.9.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
