[package]
name = "wedder"
version = "1.0.5"
description = "Current weather info for status bars like polybar"
authors = ["Adrian Wersching <dev@awersching.de>"]
edition = "2018"

[dependencies]
structopt = "0.3.4"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
toml = "0.5.5"

strum = "0.16.0"
strum_macros = "0.16.0"

directories = "2.0.2"
reqwest = "0.9.22"
chrono = "0.4.9"

log = "0.4.8"
log4rs = "0.8.3"

[dev-dependencies]
assert_cmd = "0.11.1"
