[package]
name = "wedder"
version = "1.2.0"
description = "Current weather info for status bars like polybar"
authors = ["Adrian Wersching <dev@awersching.de>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.7", features = ["blocking"] }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
toml = "0.5.6"
structopt = "0.3.16"

strum = "0.19.2"
strum_macros = "0.19.2"

directories = "3.0.1"
chrono = "0.4.13"

log = "0.4.11"
log4rs = "0.13.0"

[dev-dependencies]
assert_cmd = "1.0.1"
