[package]
name = "wedder"
version = "1.1.1"
description = "Current weather info for status bars like polybar"
authors = ["Adrian Wersching <dev@awersching.de>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.4", features = ["blocking"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
toml = "0.5.6"
structopt = "0.3.11"

strum = "0.18.0"
strum_macros = "0.18.0"

directories = "2.0.2"
chrono = "0.4.11"

log = "0.4.8"
log4rs = "0.11.0"

[dev-dependencies]
assert_cmd = "0.12.0"
