[package]
name = "wedder"
version = "1.2.0"
description = "Current weather info for status bars like polybar"
authors = ["Adrian Wersching <dev@awersching.de>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.10", features = ["blocking"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
toml = "0.5.8"
structopt = "0.3.21"

strum = "0.20.0"
strum_macros = "0.20.1"

directories = "3.0.1"
chrono = "0.4.19"

log = "0.4.11"
log4rs = "1.0.0"

[dev-dependencies]
assert_cmd = "1.0.2"
