[package]
name = "currweather"
version = "0.1.0"
authors = ["Adrian Wersching <dev@awersching.de>"]
edition = "2018"

[dependencies]
config = "0.9"
reqwest = "0.9.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
