weather_api_key = 'your api key'

# in seconds
interval = 900

city = 'London'

# available tags:
#   <icon>
#   <temperature_celsius>
#   <temperature_fahrenheit>
#   <temperature_kelvin>
format = ' <icon> <temperature_celsius>°C '
