# available weather providers:
#   OpenWeatherMap
weather_provider = 'OpenWeatherMap'
weather_api_key = 'your api key'

city = 'London'

# in seconds
interval = 300

# available tags:
#   <icon>
#   <temperature_celsius>
#   <temperature_fahrenheit>
#   <temperature_kelvin>
format = ' <icon> <temperature_celsius>°C '

# install one of the patched fonts from Nerd Fonts to display the icons:
# https://github.com/ryanoasis/nerd-fonts#patched-fonts
[icons]
ClearSky = ''
FewClouds = ''
Clouds = '摒'
ManyClouds = ''
RainSun = ''
Rain = ''
HeavyRain = '歹'
Thunderstorm = ''
Snow = ''
Mist = ''
