# available tags:
#   <city>
#   <icon>
#   <temperature>
#   <temperature_feels_like>
#   <temperature_max>
#   <temperature_min>
#   <pressure>
#   <humidity>
#   <wind_speed>
#   <cloud_percentage>
#   <sunrise>
#   <sunset>
# default: '<icon> <temperature>°C'
format = '<icon> <temperature>°C'
# in seconds
# if no interval is specified, wedder exits after printing the weather once
interval = 300

[units]
# available units:
#   Celsius
#   Fahrenheit
#   Kelvin
# default: Celsius
temperature = 'Celsius'
# available units:
#   Ms
#   Kmh
#   Mph
# default: Kmh
wind_speed = 'Kmh'

[weather]
# available providers:
#   OpenWeatherMap
# default: OpenWeatherMap
provider = 'OpenWeatherMap'
# enter your API key here
api_key = ''

[location]
# available providers:
#   Ip
#   Manual
# default: Ip
provider = 'Ip'
# if you choose 'Manual' as provider, you can set your coordinates
#lat = 51.509865
#lon = -0.118092

# install one of the patched fonts from Nerd Fonts to display the icons:
# https://github.com/ryanoasis/nerd-fonts#patched-fonts
[icons]
# the icons displayed here are also the defaults
clear_sky = ''
few_clouds = ''
clouds = ''
many_clouds = ''
rain_sun = ''
rain = ''
heavy_rain = ''
thunderstorm = ''
snow = ''
mist = ''
