name: CI

on: [push, pull_request]

env:
  PROJECT_NAME: wedder
  RUST_BACKTRACE: 1

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal
        components: rustfmt, clippy
    - uses: actions/checkout@v2
    - run: make
