name: Make

env:
  RUST_BACKTRACE: 1

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  make:
    name: Execute format, lint, test, and build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: make