name: Release

env:
  TARGET: x86_64-unknown-linux-gnu
  RUST_BACKTRACE: 1

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-20.04
    steps:
      - run: echo ::set-env name=PROJECT_NAME::${{ github.event.repository.name }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
      - uses: actions/checkout@v2
        run: make release
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ PROJECT_NAME }}-${{ GITHUB_REF_NAME }}-${{ TARGET }}