name: Release

env:
  PROJECT_NAME: wedder
  TARGET: x86_64-unknown-linux-gnu
  RUST_BACKTRACE: 1

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build executable and upload to releases page
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: make release
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{env.PROJECT_NAME}}-${{github.ref_name}}-${{env.TARGET}}