name: Release

env:
  PROJECT_NAME: wedder
  TARGET: x86_64-unknown-linux-gnu
  RUST_BACKTRACE: 1

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-20.04
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
      - uses: actions/checkout@v2
      - run: make release
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{env.PROJECT_NAME}}-${{github.ref_name}}-${{env.TARGET}}